version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: GolangStudy
    webide-port: 6800
    
    ports: # 申明端口
      webide: 6800
      ssh: 6822
      application: 3001
    
    ide-type: vscode  #vscode/theia
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install
  services:
    GolangStudy:
      container_name: GolangStudy
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123       
      volumes:
      - .:/home/project/GolangStudy
      expose:
        - 3000
      ports:
        - 3003:3001
      networks:
        - smartide-network

  networks:
    smartide-network:
      external: true
